// frontend/src/components/ui/StarRating.vue
<script setup>
import { computed } from 'vue';
import { Star } from 'lucide-vue-next';

const props = defineProps({
  value: { type: Number, default: 0 },
  count: { type: Number, default: null },
  size: { type: Number, default: 16 },
  editable: { type: Boolean, default: false }
});
const emit = defineEmits(['update:value']);

const rounded = computed(() => Math.round(props.value));
const set = (n) => props.editable && emit('update:value', n);
</script>

<template>
  <div class="inline-flex items-center gap-1">
    <div class="flex" :class="editable ? 'cursor-pointer' : ''">
      <Star
        v-for="n in 5"
        :key="n"
        :size="size"
        class="transition-colors"
        :class="n <= rounded ? 'fill-amber-400 text-amber-400' : 'text-slate-300'"
        @click="set(n)"
      />
    </div>
    <span v-if="count !== null" class="text-xs font-medium text-slate-500">
      {{ Number(value).toFixed(1) }} <span class="text-slate-400">({{ count }})</span>
    </span>
  </div>
</template>

// frontend/src/components/StarRating.jsx
import PropTypes from 'prop-types';
import FeatherIcon from 'feather-icons-react';

// Star rating: read-only display, or interactive when `onChange` is provided.
export default function StarRating({ value = 0, count, size = 16, onChange, className = '' }) {
  const rounded = Math.round(value);
  return (
    <span className={`d-inline-flex align-items-center ${className}`} style={{ gap: 2 }}>
      {[1, 2, 3, 4, 5].map((s) => (
        <FeatherIcon
          key={s}
          icon="star"
          size={size}
          onClick={onChange ? () => onChange(s) : undefined}
          style={{
            cursor: onChange ? 'pointer' : 'default',
            fill: s <= rounded ? '#f59e0b' : 'none',
            color: '#f59e0b'
          }}
        />
      ))}
      {count != null && <span className="text-muted small ms-1">({count})</span>}
    </span>
  );
}

StarRating.propTypes = {
  value: PropTypes.number,
  count: PropTypes.number,
  size: PropTypes.number,
  onChange: PropTypes.func,
  className: PropTypes.string
};
