// frontend/src/pages/store/Cart.vue
<script setup>
import { ref, computed, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import { Minus, Plus, Trash2, ShoppingBag, Tag, ArrowRight, X } from 'lucide-vue-next';
import EmptyState from '@/components/ui/EmptyState.vue';
import Spinner from '@/components/ui/Spinner.vue';
import { useAuthStore } from '@/stores/auth';
import { useCartStore } from '@/stores/cart';
import { useUiStore } from '@/stores/ui';
import { errorMessage } from '@/services/http';
import { productImage, onImgError } from '@/utils/media';

const router = useRouter();
const auth = useAuthStore();
const cart = useCartStore();
const ui = useUiStore();

const coupon = ref('');
const busyItem = ref(null);
const couponBusy = ref(false);

const currency = computed(() => cart.shopStore?.currency || '');
const data = computed(() => cart.cart);
const items = computed(() => data.value?.items || []);

const updateQty = async (item, quantity) => {
  if (quantity < 1) return;
  busyItem.value = item.id;
  try {
    await cart.updateItem(item.id, quantity);
  } catch (e) {
    ui.error(errorMessage(e));
  } finally {
    busyItem.value = null;
  }
};

const remove = async (item) => {
  busyItem.value = item.id;
  try {
    await cart.removeItem(item.id);
    ui.success('Item removed.');
  } catch (e) {
    ui.error(errorMessage(e));
  } finally {
    busyItem.value = null;
  }
};

const applyCoupon = async () => {
  if (!coupon.value.trim()) return;
  couponBusy.value = true;
  try {
    await cart.applyCoupon(coupon.value.trim());
    ui.success('Coupon applied.');
    coupon.value = '';
  } catch (e) {
    ui.error(errorMessage(e));
  } finally {
    couponBusy.value = false;
  }
};

const removeCoupon = async () => {
  couponBusy.value = true;
  try {
    await cart.removeCoupon();
  } catch (e) {
    ui.error(errorMessage(e));
  } finally {
    couponBusy.value = false;
  }
};

onMounted(() => {
  if (auth.isAuthenticated) cart.refreshCart();
});
</script>

<template>
  <div class="container py-8">
    <h1 class="mb-6 text-2xl font-bold">Your cart</h1>

    <div v-if="cart.loading && !data" class="flex min-h-[30vh] items-center justify-center">
      <Spinner :size="28" label="Loading cart…" />
    </div>

    <EmptyState
      v-else-if="!auth.isAuthenticated"
      :icon="ShoppingBag"
      title="Sign in to view your cart"
      message="Your cart is saved to your account so you can pick up where you left off."
    >
      <RouterLink :to="{ name: 'login', query: { redirect: '/cart' } }" class="btn btn-primary btn-sm">Sign in</RouterLink>
    </EmptyState>

    <EmptyState
      v-else-if="!items.length"
      :icon="ShoppingBag"
      title="Your cart is empty"
      message="Browse the marketplace and add products you love."
    >
      <RouterLink :to="{ name: 'products' }" class="btn btn-primary btn-sm">Start shopping</RouterLink>
    </EmptyState>

    <div v-else class="grid gap-8 lg:grid-cols-[1fr_360px]">
      <!-- Items -->
      <div class="space-y-4">
        <div v-if="cart.shopStore" class="text-sm text-slate-500">
          Shopping at <span class="font-semibold text-ink">{{ cart.shopStore.name }}</span>
        </div>
        <div v-for="item in items" :key="item.id" class="card flex gap-4 p-4">
          <img :src="productImage({ id: item.variant })" :alt="item.product_name" class="h-24 w-24 shrink-0 rounded-lg object-cover" @error="onImgError" />
          <div class="flex flex-1 flex-col">
            <div class="flex items-start justify-between gap-3">
              <div>
                <p class="font-semibold">{{ item.product_name }}</p>
                <p class="text-xs text-slate-400">SKU: {{ item.sku }}</p>
              </div>
              <button class="text-slate-400 hover:text-rose-600" :disabled="busyItem === item.id" @click="remove(item)">
                <Trash2 class="h-4 w-4" />
              </button>
            </div>
            <div class="mt-auto flex items-end justify-between pt-3">
              <div class="inline-flex items-center rounded-lg border border-slate-200">
                <button class="grid h-8 w-8 place-items-center text-slate-600 hover:bg-slate-100 disabled:opacity-40" :disabled="item.quantity <= 1 || busyItem === item.id" @click="updateQty(item, item.quantity - 1)">
                  <Minus class="h-3.5 w-3.5" />
                </button>
                <span class="w-9 text-center text-sm font-semibold">{{ item.quantity }}</span>
                <button class="grid h-8 w-8 place-items-center text-slate-600 hover:bg-slate-100 disabled:opacity-40" :disabled="busyItem === item.id" @click="updateQty(item, item.quantity + 1)">
                  <Plus class="h-3.5 w-3.5" />
                </button>
              </div>
              <div class="text-right">
                <p class="font-bold">{{ item.line_total }} {{ currency }}</p>
                <p class="text-xs text-slate-400">{{ item.unit_price }} each</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Summary -->
      <aside class="h-fit space-y-4 lg:sticky lg:top-24">
        <div class="card p-5">
          <h3 class="font-semibold">Order summary</h3>

          <div class="mt-4">
            <div v-if="data.coupon_code" class="flex items-center justify-between rounded-lg bg-emerald-50 px-3 py-2 text-sm text-emerald-700">
              <span class="flex items-center gap-1.5"><Tag class="h-4 w-4" /> {{ data.coupon_code }}</span>
              <button class="text-emerald-700 hover:text-emerald-900" :disabled="couponBusy" @click="removeCoupon"><X class="h-4 w-4" /></button>
            </div>
            <form v-else class="flex gap-2" @submit.prevent="applyCoupon">
              <input v-model="coupon" placeholder="Coupon code" class="input" />
              <button class="btn btn-outline btn-sm shrink-0" :disabled="couponBusy || !coupon.trim()">Apply</button>
            </form>
          </div>

          <dl class="mt-5 space-y-2 border-t border-slate-100 pt-4 text-sm">
            <div class="flex justify-between"><dt class="text-slate-500">Subtotal</dt><dd class="font-medium">{{ data.subtotal }} {{ currency }}</dd></div>
            <div v-if="Number(data.discount) > 0" class="flex justify-between text-emerald-600"><dt>Discount</dt><dd>−{{ data.discount }} {{ currency }}</dd></div>
            <div class="flex justify-between border-t border-slate-100 pt-2 text-base font-bold">
              <dt>Total</dt><dd>{{ data.total }} {{ currency }}</dd>
            </div>
          </dl>

          <RouterLink :to="{ name: 'checkout' }" class="btn btn-primary btn-lg mt-5 w-full">
            Checkout <ArrowRight class="h-4 w-4" />
          </RouterLink>
        </div>
        <RouterLink :to="{ name: 'products' }" class="block text-center text-sm font-medium text-primary-600 hover:underline">
          Continue shopping
        </RouterLink>
      </aside>
    </div>
  </div>
</template>

// frontend/src/views/storefront/Cart.jsx
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Alert, Button, Card, Form, InputGroup, Spinner, Table } from 'react-bootstrap';
import FeatherIcon from 'feather-icons-react';

import { errorMessage } from 'api/client';
import { useAuth } from 'contexts/AuthContext';
import { useCart } from 'contexts/CartContext';
import { onImgError, productImage } from 'utils/media';

export default function Cart() {
  const { isAuthenticated } = useAuth();
  const { cart, shopStore, loading, updateItem, removeItem, applyCoupon, removeCoupon } = useCart();
  const [error, setError] = useState('');
  const [busyId, setBusyId] = useState('');
  const [coupon, setCoupon] = useState('');
  const [couponBusy, setCouponBusy] = useState(false);

  const currency = shopStore?.currency || '';

  const onCoupon = async (e) => {
    e.preventDefault();
    if (!coupon.trim()) return;
    setCouponBusy(true);
    setError('');
    try {
      await applyCoupon(coupon.trim());
      setCoupon('');
    } catch (err) {
      setError(errorMessage(err));
    } finally {
      setCouponBusy(false);
    }
  };

  const act = async (fn) => {
    setError('');
    try {
      await fn();
    } catch (e) {
      setError(errorMessage(e));
    } finally {
      setBusyId('');
    }
  };

  if (!isAuthenticated) {
    return (
      <Alert variant="info">
        Please <Link to="/login">sign in</Link> to view your cart.
      </Alert>
    );
  }

  const items = cart?.items || [];

  return (
    <>
      <h3 className="fw-bold mb-3">Your cart</h3>
      {error && <Alert variant="danger">{error}</Alert>}

      {loading && !cart ? (
        <div className="text-center py-5">
          <Spinner animation="border" variant="primary" />
        </div>
      ) : items.length === 0 ? (
        <Alert variant="info">
          Your cart is empty. <Link to="/">Browse stores →</Link>
        </Alert>
      ) : (
        <Card className="border-0 shadow-sm">
          <Card.Body>
            <Table responsive className="align-middle mb-0">
              <thead>
                <tr>
                  <th>Product</th>
                  <th>Price</th>
                  <th style={{ width: 150 }}>Qty</th>
                  <th className="text-end">Line total</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                {items.map((it) => (
                  <tr key={it.id}>
                    <td>
                      <div className="d-flex align-items-center gap-3">
                        <img
                          src={productImage({ id: it.sku, slug: it.sku }, 120, 120)}
                          alt=""
                          className="thumb"
                          onError={onImgError(it.sku)}
                        />
                        <div>
                          <div className="fw-semibold">{it.product_name}</div>
                          <div className="small text-muted">{it.sku}</div>
                        </div>
                      </div>
                    </td>
                    <td>
                      {it.unit_price} {currency}
                    </td>
                    <td>
                      <div className="d-flex align-items-center gap-2">
                        <Button
                          size="sm"
                          variant="outline-secondary"
                          disabled={busyId === it.id}
                          onClick={() => {
                            setBusyId(it.id);
                            act(() => updateItem(it.id, it.quantity - 1));
                          }}
                        >
                          −
                        </Button>
                        <span>{it.quantity}</span>
                        <Button
                          size="sm"
                          variant="outline-secondary"
                          disabled={busyId === it.id}
                          onClick={() => {
                            setBusyId(it.id);
                            act(() => updateItem(it.id, it.quantity + 1));
                          }}
                        >
                          +
                        </Button>
                      </div>
                    </td>
                    <td className="text-end fw-semibold">
                      {it.line_total} {currency}
                    </td>
                    <td className="text-end">
                      <Button
                        size="sm"
                        variant="link"
                        className="text-danger p-0"
                        onClick={() => {
                          setBusyId(it.id);
                          act(() => removeItem(it.id));
                        }}
                      >
                        <FeatherIcon icon="trash-2" size={16} />
                      </Button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </Table>

            <div className="row mt-3 pt-3 border-top g-3">
              <div className="col-md-6">
                {cart.coupon_code ? (
                  <div className="d-flex align-items-center gap-2">
                    <span className="badge bg-success">Coupon: {cart.coupon_code}</span>
                    <Button size="sm" variant="link" className="text-danger p-0" onClick={removeCoupon}>
                      remove
                    </Button>
                  </div>
                ) : (
                  <Form onSubmit={onCoupon} style={{ maxWidth: 320 }}>
                    <InputGroup size="sm">
                      <Form.Control placeholder="Coupon code" value={coupon} onChange={(e) => setCoupon(e.target.value)} />
                      <Button type="submit" variant="outline-primary" disabled={couponBusy}>
                        {couponBusy ? <Spinner animation="border" size="sm" /> : 'Apply'}
                      </Button>
                    </InputGroup>
                  </Form>
                )}
                <Button as={Link} to="/" variant="link" className="text-decoration-none ps-0 mt-2">
                  <FeatherIcon icon="arrow-left" size={16} /> Continue shopping
                </Button>
              </div>
              <div className="col-md-6 text-md-end">
                <div className="text-muted">
                  Subtotal: {cart.subtotal} {currency}
                </div>
                {Number(cart.discount) > 0 && (
                  <div className="text-success">
                    Discount: −{cart.discount} {currency}
                  </div>
                )}
                <div className="h5 my-2">
                  Total: {cart.total} {currency}
                </div>
                <Button as={Link} to="/checkout" variant="primary">
                  Checkout <FeatherIcon icon="arrow-right" size={16} />
                </Button>
              </div>
            </div>
          </Card.Body>
        </Card>
      )}
    </>
  );
}
