// frontend/src/views/storefront/Checkout.jsx
import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Alert, Button, Card, Col, Form, Row, Spinner } from 'react-bootstrap';
import FeatherIcon from 'feather-icons-react';

import api, { errorMessage } from 'api/client';
import { useAuth } from 'contexts/AuthContext';
import { useCart } from 'contexts/CartContext';
import { onImgError, productImage } from 'utils/media';

const asList = (d) => (Array.isArray(d) ? d : d?.results || []);

export default function Checkout() {
  const { isAuthenticated } = useAuth();
  const { cart, shopStore, checkout } = useCart();
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [order, setOrder] = useState(null);
  const [addresses, setAddresses] = useState([]);
  const [methods, setMethods] = useState([]);
  const [addressId, setAddressId] = useState('');
  const [methodId, setMethodId] = useState('');

  const currency = shopStore?.currency || '';
  const headers = shopStore ? { 'X-Store-Id': shopStore.id } : {};

  const loadMethods = useCallback(
    async (country) => {
      if (!shopStore) return;
      const res = await api
        .get('/shipping/methods/', { headers: { 'X-Store-Id': shopStore.id }, params: country ? { country } : {} })
        .then((r) => asList(r.data))
        .catch(() => []);
      setMethods(res);
    },
    [shopStore]
  );

  useEffect(() => {
    if (!shopStore) return;
    api
      .get('/addresses/', { headers: { 'X-Store-Id': shopStore.id } })
      .then((r) => {
        const list = asList(r.data);
        setAddresses(list);
        const def = list.find((a) => a.is_default);
        if (def) setAddressId(def.id);
      })
      .catch(() => {});
    loadMethods();
  }, [shopStore, loadMethods]);

  if (!isAuthenticated) {
    return (
      <Alert variant="info">
        Please <Link to="/login">sign in</Link> to check out.
      </Alert>
    );
  }

  if (order) {
    return (
      <div className="text-center py-4" style={{ maxWidth: 520, margin: '0 auto' }}>
        <div className="text-success mb-3">
          <FeatherIcon icon="check-circle" size={56} />
        </div>
        <h3 className="fw-bold">Order placed!</h3>
        <p className="text-muted">
          Order <strong>{order.number}</strong> — {order.total} {order.currency || currency}
        </p>
        <div className="d-flex gap-2 justify-content-center mt-4">
          <Button as={Link} to="/account" variant="primary">
            My orders
          </Button>
          <Button as={Link} to="/products" variant="outline-secondary">
            Continue shopping
          </Button>
        </div>
      </div>
    );
  }

  const items = cart?.items || [];
  if (items.length === 0) {
    return (
      <Alert variant="info">
        Your cart is empty. <Link to="/products">Browse products →</Link>
      </Alert>
    );
  }

  const onAddress = (id) => {
    setAddressId(id);
    const addr = addresses.find((a) => a.id === id);
    loadMethods(addr?.country);
    setMethodId('');
  };

  const placeOrder = async () => {
    setBusy(true);
    setError('');
    try {
      setOrder(await checkout({ address_id: addressId || null, shipping_method_id: methodId || null }));
    } catch (e) {
      setError(errorMessage(e));
    } finally {
      setBusy(false);
    }
  };

  const selectedMethod = methods.find((m) => m.id === methodId);

  return (
    <>
      <h3 className="fw-bold mb-3">Checkout</h3>
      {error && <Alert variant="danger">{error}</Alert>}
      <Row className="g-4">
        <Col md={7}>
          <Card className="border-0 shadow-sm mb-3">
            <Card.Header className="bg-white fw-semibold">Shipping address</Card.Header>
            <Card.Body>
              {addresses.length === 0 ? (
                <div className="small text-muted">
                  No saved addresses. <Link to="/account">Add one in your account</Link> (optional).
                </div>
              ) : (
                <Form.Select value={addressId} onChange={(e) => onAddress(e.target.value)}>
                  <option value="">No address</option>
                  {addresses.map((a) => (
                    <option key={a.id} value={a.id}>
                      {[a.full_name || a.label, a.line1, a.city, a.country].filter(Boolean).join(', ')}
                    </option>
                  ))}
                </Form.Select>
              )}
            </Card.Body>
          </Card>

          <Card className="border-0 shadow-sm mb-3">
            <Card.Header className="bg-white fw-semibold">Shipping method</Card.Header>
            <Card.Body>
              {methods.length === 0 ? (
                <div className="small text-muted">No shipping methods — delivery is free for this order.</div>
              ) : (
                <>
                  <Form.Check
                    type="radio"
                    name="ship"
                    id="ship-none"
                    label="No shipping (free)"
                    checked={!methodId}
                    onChange={() => setMethodId('')}
                    className="mb-2"
                  />
                  {methods.map((m) => (
                    <Form.Check
                      key={m.id}
                      type="radio"
                      name="ship"
                      id={`ship-${m.id}`}
                      checked={methodId === m.id}
                      onChange={() => setMethodId(m.id)}
                      className="mb-2"
                      label={
                        <span className="d-flex justify-content-between" style={{ width: 260 }}>
                          <span>{m.name} <span className="text-muted small">· {m.zone_name}</span></span>
                          <span>{Number(m.price) === 0 ? 'Free' : `${m.price} ${currency}`}</span>
                        </span>
                      }
                    />
                  ))}
                </>
              )}
            </Card.Body>
          </Card>

          <Card className="border-0 shadow-sm">
            <Card.Header className="bg-white fw-semibold">Items</Card.Header>
            <Card.Body>
              {items.map((it) => (
                <div key={it.id} className="d-flex align-items-center justify-content-between border-bottom py-2">
                  <span className="d-flex align-items-center gap-2">
                    <img src={productImage({ id: it.sku, slug: it.sku }, 100, 100)} alt="" className="thumb" style={{ width: 40, height: 40 }} onError={onImgError(it.sku)} />
                    {it.product_name} <span className="text-muted small">× {it.quantity}</span>
                  </span>
                  <span>{it.line_total} {currency}</span>
                </div>
              ))}
            </Card.Body>
          </Card>
        </Col>

        <Col md={5}>
          <Card className="border-0 shadow-sm">
            <Card.Body>
              <div className="d-flex justify-content-between">
                <span className="text-muted">Subtotal</span>
                <span>{cart.subtotal} {currency}</span>
              </div>
              {Number(cart.discount) > 0 && (
                <div className="d-flex justify-content-between text-success">
                  <span>Discount{cart.coupon_code ? ` (${cart.coupon_code})` : ''}</span>
                  <span>−{cart.discount} {currency}</span>
                </div>
              )}
              {selectedMethod && (
                <div className="d-flex justify-content-between">
                  <span className="text-muted">Shipping</span>
                  <span>{Number(selectedMethod.price) === 0 ? 'Free' : `${selectedMethod.price} ${currency}`}</span>
                </div>
              )}
              <div className="small text-muted mt-1">Tax &amp; final shipping are calculated when the order is placed.</div>
              <div className="d-flex justify-content-between h5 mt-2 pt-2 border-top">
                <span>Total</span>
                <span>{cart.total} {currency}</span>
              </div>
              <Button variant="primary" className="w-100 mt-3" onClick={placeOrder} disabled={busy}>
                {busy ? <Spinner animation="border" size="sm" /> : 'Place order'}
              </Button>
              <div className="small text-muted text-center mt-2">Demo checkout — no real payment is taken.</div>
            </Card.Body>
          </Card>
        </Col>
      </Row>
    </>
  );
}

// frontend/src/pages/store/Checkout.vue
<script setup>
import { ref, computed, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import { Plus, MapPin, Lock, Check } from 'lucide-vue-next';
import FormField from '@/components/ui/FormField.vue';
import Spinner from '@/components/ui/Spinner.vue';
import EmptyState from '@/components/ui/EmptyState.vue';
import { useCartStore } from '@/stores/cart';
import { useUiStore } from '@/stores/ui';
import { shop } from '@/services/shop';
import { errorMessage } from '@/services/http';

const router = useRouter();
const cart = useCartStore();
const ui = useUiStore();

const loading = ref(true);
const placing = ref(false);
const addresses = ref([]);
const selectedAddress = ref(null);
const showForm = ref(false);
const savingAddress = ref(false);

const blankAddress = () => ({
  label: 'Home',
  full_name: '',
  line1: '',
  line2: '',
  city: '',
  region: '',
  postal_code: '',
  country: cart.shopStore?.country || '',
  phone: '',
  is_default: true
});
const form = ref(blankAddress());

const currency = computed(() => cart.shopStore?.currency || '');
const data = computed(() => cart.cart);
const items = computed(() => data.value?.items || []);

const loadAddresses = async () => {
  try {
    const res = await shop.addresses(cart.headers);
    addresses.value = res.data?.results || res.data || [];
    const def = addresses.value.find((a) => a.is_default) || addresses.value[0];
    selectedAddress.value = def?.id || null;
    showForm.value = addresses.value.length === 0;
  } catch {
    addresses.value = [];
    showForm.value = true;
  }
};

const saveAddress = async () => {
  savingAddress.value = true;
  try {
    const res = await shop.createAddress(cart.headers, form.value);
    const created = res.data;
    addresses.value.push(created);
    selectedAddress.value = created.id;
    showForm.value = false;
    form.value = blankAddress();
    ui.success('Address saved.');
  } catch (e) {
    ui.error(errorMessage(e));
  } finally {
    savingAddress.value = false;
  }
};

const placeOrder = async () => {
  placing.value = true;
  try {
    const chosen = addresses.value.find((a) => a.id === selectedAddress.value);
    const order = await cart.checkout({
      address_id: selectedAddress.value || undefined,
      country: chosen?.country || cart.shopStore?.country || '',
      currency: cart.shopStore?.currency || ''
    });
    ui.success('Order placed successfully!');
    router.push({ name: 'order-confirmation', params: { id: order.id } });
  } catch (e) {
    ui.error(errorMessage(e));
  } finally {
    placing.value = false;
  }
};

onMounted(async () => {
  await cart.refreshCart();
  await loadAddresses();
  loading.value = false;
});
</script>

<template>
  <div class="container py-8">
    <h1 class="mb-6 text-2xl font-bold">Checkout</h1>

    <div v-if="loading" class="flex min-h-[30vh] items-center justify-center">
      <Spinner :size="28" label="Preparing checkout…" />
    </div>

    <EmptyState
      v-else-if="!items.length"
      title="Your cart is empty"
      message="Add items to your cart before checking out."
    >
      <RouterLink :to="{ name: 'products' }" class="btn btn-primary btn-sm">Browse products</RouterLink>
    </EmptyState>

    <div v-else class="grid gap-8 lg:grid-cols-[1fr_360px]">
      <!-- Left: shipping -->
      <div class="space-y-6">
        <section class="card p-6">
          <div class="mb-4 flex items-center justify-between">
            <h2 class="flex items-center gap-2 font-semibold"><MapPin class="h-5 w-5 text-primary-600" /> Shipping address</h2>
            <button v-if="addresses.length" class="btn btn-ghost btn-sm" @click="showForm = !showForm">
              <Plus class="h-4 w-4" /> New address
            </button>
          </div>

          <div v-if="addresses.length" class="grid gap-3 sm:grid-cols-2">
            <label
              v-for="a in addresses"
              :key="a.id"
              class="flex cursor-pointer gap-3 rounded-lg border p-3 transition"
              :class="selectedAddress === a.id ? 'border-primary-500 bg-primary-50/50' : 'border-slate-200 hover:border-slate-300'"
            >
              <input v-model="selectedAddress" type="radio" :value="a.id" class="mt-1 text-primary-600 focus:ring-primary-500" />
              <div class="text-sm">
                <p class="font-semibold">{{ a.full_name }} <span class="text-xs font-normal text-slate-400">· {{ a.label }}</span></p>
                <p class="text-slate-500">{{ a.line1 }}<span v-if="a.line2">, {{ a.line2 }}</span></p>
                <p class="text-slate-500">{{ a.city }}, {{ a.region }} {{ a.postal_code }}</p>
                <p class="text-slate-500">{{ a.country }} · {{ a.phone }}</p>
              </div>
            </label>
          </div>

          <form v-if="showForm" class="mt-4 grid gap-4 border-t border-slate-100 pt-4 sm:grid-cols-2" @submit.prevent="saveAddress">
            <FormField v-model="form.full_name" label="Full name" required class="sm:col-span-2" />
            <FormField v-model="form.line1" label="Address line 1" required class="sm:col-span-2" />
            <FormField v-model="form.line2" label="Address line 2" />
            <FormField v-model="form.city" label="City" required />
            <FormField v-model="form.region" label="State / Region" />
            <FormField v-model="form.postal_code" label="Postal code" required />
            <FormField v-model="form.country" label="Country (ISO-2)" maxlength="2" placeholder="US" required />
            <FormField v-model="form.phone" label="Phone" />
            <div class="sm:col-span-2">
              <button type="submit" class="btn btn-primary btn-sm" :disabled="savingAddress">
                <Spinner v-if="savingAddress" :size="16" /><span v-else>Save address</span>
              </button>
            </div>
          </form>
        </section>
      </div>

      <!-- Right: summary -->
      <aside class="h-fit space-y-4 lg:sticky lg:top-24">
        <div class="card p-5">
          <h3 class="font-semibold">Order summary</h3>
          <ul class="mt-4 space-y-3 border-b border-slate-100 pb-4">
            <li v-for="item in items" :key="item.id" class="flex justify-between gap-2 text-sm">
              <span class="text-slate-600">{{ item.product_name }} <span class="text-slate-400">× {{ item.quantity }}</span></span>
              <span class="font-medium">{{ item.line_total }} {{ currency }}</span>
            </li>
          </ul>
          <dl class="mt-4 space-y-2 text-sm">
            <div class="flex justify-between"><dt class="text-slate-500">Subtotal</dt><dd class="font-medium">{{ data.subtotal }} {{ currency }}</dd></div>
            <div v-if="Number(data.discount) > 0" class="flex justify-between text-emerald-600"><dt>Discount</dt><dd>−{{ data.discount }} {{ currency }}</dd></div>
            <div class="flex justify-between border-t border-slate-100 pt-2 text-base font-bold"><dt>Total</dt><dd>{{ data.total }} {{ currency }}</dd></div>
          </dl>
          <button class="btn btn-primary btn-lg mt-5 w-full" :disabled="placing" @click="placeOrder">
            <Spinner v-if="placing" :size="18" />
            <template v-else><Lock class="h-4 w-4" /> Place order</template>
          </button>
          <p class="mt-3 flex items-center justify-center gap-1 text-xs text-slate-400">
            <Check class="h-3.5 w-3.5" /> Secure, encrypted checkout
          </p>
        </div>
      </aside>
    </div>
  </div>
</template>
