// frontend/src/views/team/Team.jsx
import { useCallback, useEffect, useState } from 'react';
import { Alert, Badge, Button, Card, Col, Form, InputGroup, Row, Spinner, Table } from 'react-bootstrap';
import FeatherIcon from 'feather-icons-react';

import api, { errorMessage } from 'api/client';
import { useStore } from 'contexts/StoreContext';

const ROLES = ['employee', 'manager', 'owner'];
const ROLE_VARIANT = { owner: 'primary', manager: 'info', employee: 'secondary' };

export default function Team() {
  const { activeStore } = useStore();
  const [members, setMembers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [email, setEmail] = useState('');
  const [role, setRole] = useState('employee');
  const [busy, setBusy] = useState(false);

  const base = activeStore ? `/stores/${activeStore.id}/members/` : null;

  const load = useCallback(async () => {
    if (!base) {
      setLoading(false);
      return;
    }
    setLoading(true);
    setError('');
    try {
      const res = await api.get(base);
      setMembers(Array.isArray(res.data) ? res.data : res.data?.results || []);
    } catch (e) {
      setError(errorMessage(e));
    } finally {
      setLoading(false);
    }
  }, [base]);

  useEffect(() => {
    load();
  }, [load]);

  const invite = async (e) => {
    e.preventDefault();
    if (!email.trim()) return;
    setBusy(true);
    setError('');
    setNotice('');
    try {
      await api.post(base, { email: email.trim(), role });
      setNotice(`${email.trim()} added as ${role}.`);
      setEmail('');
      setRole('employee');
      load();
    } catch (err) {
      setError(errorMessage(err));
    } finally {
      setBusy(false);
    }
  };

  const changeRole = async (m, newRole) => {
    setError('');
    try {
      await api.patch(`${base}${m.id}/`, { role: newRole });
      load();
    } catch (e) {
      setError(errorMessage(e));
    }
  };

  const remove = async (m) => {
    if (!window.confirm(`Remove ${m.user_email} from this store's team?`)) return;
    setError('');
    try {
      await api.delete(`${base}${m.id}/`);
      load();
    } catch (e) {
      setError(errorMessage(e));
    }
  };

  if (!activeStore) return <Alert variant="info">Select a store from the top bar to manage its team.</Alert>;

  return (
    <Row className="g-4">
      <Col md={12}>
        <div className="d-flex align-items-center justify-content-between mb-1">
          <h5 className="mb-0">Team — {activeStore.name}</h5>
          <span className="text-muted small">{members.length} member(s)</span>
        </div>
        <p className="text-muted small">
          Store owners and managers can invite staff. Roles: <strong>owner</strong> (full control),{' '}
          <strong>manager</strong> (manage catalog, orders, staff invites), <strong>employee</strong> (day-to-day operations).
        </p>
      </Col>

      <Col lg={4}>
        <Card>
          <Card.Header>
            <h6 className="mb-0">Invite a team member</h6>
          </Card.Header>
          <Card.Body>
            {notice && <Alert variant="success" className="py-2">{notice}</Alert>}
            {error && <Alert variant="danger" className="py-2">{error}</Alert>}
            <Form onSubmit={invite}>
              <Form.Group className="mb-3">
                <Form.Label>Email</Form.Label>
                <InputGroup>
                  <InputGroup.Text>
                    <FeatherIcon icon="mail" size={16} />
                  </InputGroup.Text>
                  <Form.Control type="email" placeholder="staff@example.com" value={email} onChange={(e) => setEmail(e.target.value)} required />
                </InputGroup>
                <Form.Text className="text-muted">The person must already have an account.</Form.Text>
              </Form.Group>
              <Form.Group className="mb-3">
                <Form.Label>Role</Form.Label>
                <Form.Select value={role} onChange={(e) => setRole(e.target.value)}>
                  {ROLES.filter((r) => r !== 'owner').map((r) => (
                    <option key={r} value={r}>
                      {r}
                    </option>
                  ))}
                </Form.Select>
              </Form.Group>
              <Button type="submit" variant="primary" disabled={busy}>
                {busy ? <Spinner animation="border" size="sm" /> : (
                  <>
                    <FeatherIcon icon="user-plus" size={16} className="me-1" /> Add member
                  </>
                )}
              </Button>
            </Form>
          </Card.Body>
        </Card>
      </Col>

      <Col lg={8}>
        <Card>
          <Card.Header>
            <h6 className="mb-0">Members</h6>
          </Card.Header>
          <Card.Body className="p-0">
            {loading ? (
              <div className="text-center py-5">
                <Spinner animation="border" variant="primary" />
              </div>
            ) : (
              <Table responsive hover className="align-middle mb-0">
                <thead>
                  <tr>
                    <th className="ps-3">Member</th>
                    <th>Role</th>
                    <th>Status</th>
                    <th className="text-end pe-3">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {members.length === 0 && (
                    <tr>
                      <td colSpan={4} className="text-center text-muted py-4">No team members yet.</td>
                    </tr>
                  )}
                  {members.map((m) => (
                    <tr key={m.id}>
                      <td className="ps-3">{m.user_email}</td>
                      <td>
                        {m.role === 'owner' ? (
                          <Badge bg={ROLE_VARIANT.owner}>owner</Badge>
                        ) : (
                          <Form.Select size="sm" value={m.role} style={{ maxWidth: 150 }} onChange={(e) => changeRole(m, e.target.value)}>
                            {ROLES.map((r) => (
                              <option key={r} value={r}>
                                {r}
                              </option>
                            ))}
                          </Form.Select>
                        )}
                      </td>
                      <td>
                        <Badge bg={m.is_active ? 'success' : 'secondary'}>{m.is_active ? 'active' : 'inactive'}</Badge>
                      </td>
                      <td className="text-end pe-3">
                        {m.role !== 'owner' && (
                          <Button size="sm" variant="link" className="text-danger p-0" onClick={() => remove(m)} title="Remove">
                            <FeatherIcon icon="trash-2" size={16} />
                          </Button>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </Table>
            )}
          </Card.Body>
        </Card>
      </Col>
    </Row>
  );
}

// frontend/src/pages/admin/Team.vue
<script setup>
import { ref, onMounted } from 'vue';
import { UserPlus, Trash2 } from 'lucide-vue-next';
import PageHeader from '@/components/ui/PageHeader.vue';
import DataTable from '@/components/ui/DataTable.vue';
import StatusBadge from '@/components/ui/StatusBadge.vue';
import Modal from '@/components/ui/Modal.vue';
import FormField from '@/components/ui/FormField.vue';
import Spinner from '@/components/ui/Spinner.vue';
import { useTenantStore } from '@/stores/tenant';
import { useUiStore } from '@/stores/ui';
import { seller } from '@/services/seller';
import { errorMessage } from '@/services/http';

const tenant = useTenantStore();
const ui = useUiStore();

const roles = ['manager', 'employee'];
const loading = ref(true);
const members = ref([]);
const storeId = ref(null);

const columns = [
  { key: 'user_email', label: 'Member' },
  { key: 'role', label: 'Role' },
  { key: 'is_active', label: 'Status' },
  { key: 'created_at', label: 'Joined' },
  { key: 'actions', label: '', align: 'right' }
];

const load = async () => {
  loading.value = true;
  try {
    storeId.value = await tenant.ensureReady();
    if (!storeId.value) return;
    const res = await seller.members(storeId.value);
    members.value = res.data?.results || res.data || [];
  } catch (e) {
    ui.error(errorMessage(e));
  } finally {
    loading.value = false;
  }
};

const showInvite = ref(false);
const inviting = ref(false);
const form = ref({ email: '', role: 'employee' });

const invite = async () => {
  inviting.value = true;
  try {
    await seller.addMember(storeId.value, form.value);
    ui.success('Member added.');
    showInvite.value = false;
    form.value = { email: '', role: 'employee' };
    load();
  } catch (e) {
    ui.error(errorMessage(e));
  } finally {
    inviting.value = false;
  }
};

const changeRole = async (member, role) => {
  try {
    await seller.updateMember(storeId.value, member.id, { role });
    member.role = role;
    ui.success('Role updated.');
  } catch (e) {
    ui.error(errorMessage(e));
  }
};

const confirmRemove = ref(null);
const removing = ref(false);
const doRemove = async () => {
  removing.value = true;
  try {
    await seller.removeMember(storeId.value, confirmRemove.value.id);
    ui.success('Member removed.');
    confirmRemove.value = null;
    load();
  } catch (e) {
    ui.error(errorMessage(e));
  } finally {
    removing.value = false;
  }
};

onMounted(load);
</script>

<template>
  <div>
    <PageHeader title="Team" subtitle="Manage who can access this store.">
      <template #actions>
        <span v-if="!tenant.canAdminTeam" class="chip border-slate-200 bg-slate-100 text-slate-600">Owners manage roles</span>
        <button v-if="tenant.canManageMembers" class="btn btn-primary btn-sm" :disabled="!tenant.hasStores" @click="showInvite = true">
          <UserPlus class="h-4 w-4" /> Add member
        </button>
      </template>
    </PageHeader>

    <DataTable :columns="columns" :rows="members" :loading="loading" empty-title="No team members" empty-message="Invite people to help run your store.">
      <template #cell-user_email="{ row }">
        <div class="flex items-center gap-3">
          <span class="grid h-9 w-9 place-items-center rounded-full bg-primary-100 text-sm font-semibold text-primary-700">
            {{ (row.user_email || '?').charAt(0).toUpperCase() }}
          </span>
          <span class="font-medium text-ink">{{ row.user_email }}</span>
        </div>
      </template>
      <template #cell-role="{ row }">
        <select
          v-if="tenant.canAdminTeam && row.role !== 'owner'"
          :value="row.role"
          class="input h-9 max-w-[140px] py-1 text-sm capitalize"
          @change="changeRole(row, $event.target.value)"
        >
          <option v-for="r in roles" :key="r" :value="r" class="capitalize">{{ r }}</option>
        </select>
        <StatusBadge v-else :status="row.role === 'owner' ? 'indigo' : 'gray'" :label="row.role" />
      </template>
      <template #cell-is_active="{ value }"><StatusBadge :status="value ? 'active' : 'inactive'" /></template>
      <template #cell-created_at="{ value }">{{ (value || '').slice(0, 10) }}</template>
      <template #cell-actions="{ row }">
        <button v-if="tenant.canAdminTeam && row.role !== 'owner'" class="btn btn-ghost btn-sm text-rose-600" @click="confirmRemove = row">
          <Trash2 class="h-4 w-4" />
        </button>
      </template>
    </DataTable>

    <Modal v-model="showInvite" title="Add team member">
      <form id="invite-form" class="grid gap-4" @submit.prevent="invite">
        <FormField v-model="form.email" label="Email address" type="email" placeholder="teammate@example.com" required />
        <div>
          <label class="label">Role</label>
          <select v-model="form.role" class="input capitalize">
            <option v-for="r in roles" :key="r" :value="r" class="capitalize">{{ r }}</option>
          </select>
        </div>
      </form>
      <template #footer>
        <div class="flex justify-end gap-2">
          <button class="btn btn-ghost" @click="showInvite = false">Cancel</button>
          <button form="invite-form" type="submit" class="btn btn-primary" :disabled="inviting">
            <Spinner v-if="inviting" :size="18" /><span v-else>Add member</span>
          </button>
        </div>
      </template>
    </Modal>

    <Modal :model-value="!!confirmRemove" title="Remove member" size="sm" @update:model-value="confirmRemove = null">
      <p class="text-sm text-slate-600">Remove <span class="font-semibold">{{ confirmRemove?.user_email }}</span> from this store?</p>
      <template #footer>
        <div class="flex justify-end gap-2">
          <button class="btn btn-ghost" @click="confirmRemove = null">Cancel</button>
          <button class="btn btn-danger" :disabled="removing" @click="doRemove">
            <Spinner v-if="removing" :size="18" /><span v-else>Remove</span>
          </button>
        </div>
      </template>
    </Modal>
  </div>
</template>
